- name: "Bottle"
  id: 0
  frame_id: "base_link"
  size: [0.0, 0.0, 0.0]
- name: "Cheezeit"
  id: 1
  frame_id: "base_link"
  size: [0.03, 0.2, 0.0]
- name: "Cup"
  id: 2
  frame_id: "base_link"
  size: [0.0, 0.0, 0.0]
- name: "Pringles" # cylinder
  id: 3
  frame_id: "base_link"
  size: [0.03, 0.2, 0.0]
# - name: "Mustard"
#   id: 3
#   frame_id: "base_link"
#   size: [0.03, 0.2, 0.0]



  # - name: "Spam"
  # id: 1
  # frame_id: "world"
  # size: [0.0, 0.0, 0.0]