- object_id: "table1"
  key: "static"
  header_frame_id: "world"
  primitive_types: [[1]]
  primitive_dimensions: [[.913, .913, .04]]
  primitive_poses: [[0.0, 0.0, 0.755, 0, 0, 0, 1]]
  subframe_names: ["center", "left"]
  subframe_poses: [[-.4, 0.0, .777, 0, 0, 0, 1], [-.4, -0.1, 0.777, 0, 0, 0, 1]]
  mesh_poses: []
- object_id: "sponge"
  key: "object"
  header_frame_id: "world"
  primitive_types: [[1]]
  primitive_dimensions: [[0.05, 0.1, 0.02]]
  primitive_poses: [[0.0, 0.0, 0.0, 0, 0, 0, 1]]
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
# - object_id: "cylinder"
#   key: "object"
#   header_frame_id: "world"
#   primitive_types: [[3]]
#   primitive_dimensions: [[0.1, 0.02, 0.0]]
#   primitive_poses: [[0.0, 0.0, 0.0, 0, 0, 0, 1]]
#   subframe_names: []
#   subframe_poses: []
#   mesh_poses: []
- object_id: "glass"
  key: "mesh"
  header_frame_id: "world"
  primitive_types: []
  primitive_dimensions: []
  primitive_poses: []
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
- object_id: "bottle"
  key: "mesh"
  header_frame_id: "world"
  primitive_types: []
  primitive_dimensions: []
  primitive_poses: []
  subframe_names: []
  subframe_poses: []
  mesh_poses: []