- object_id: "table1"
  key: "static"
  header_frame_id: "world"
  primitive_types: [[1]]
  primitive_dimensions: [[.913, .913, .04]]
  primitive_poses: [[0.0, 0.0, 0.755, 0, 0, 0, 1]]
  subframe_names: ["surface"]
  subframe_poses: [[0.0, 0.0, 0.755, 0, 0, 0, 1]]
  mesh_poses: []
- object_id: "sponge"
  key: ""
  header_frame_id: "world"
  primitive_types: [[1]]
  primitive_dimensions: [[0.05, 0.1, 0.02]]
  primitive_poses: [[0.0, 0.0, 0.0, 0, 0, 0, 1]]
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
- object_id: "bottle"
  key: "mesh"
  header_frame_id: "world"
  primitive_types: []
  primitive_dimensions: []
  primitive_poses: []
  subframe_names: []
  subframe_poses: []
  mesh_poses: []