- object_id: "Table"
  key: "surface"
  header_frame_id: "world"
  primitive_types: [[1]]
  primitive_dimensions: [[.75, 1.52, .04]]
  primitive_poses: [[0.0, 0.0, 0.645, 0, 0, 0, 1]]
  subframe_names: ["center", "left", "far left"]
  subframe_poses: [[-.25, -.3, 0.665, 0, 0, 0, 1], [-.25, -.1, 0.665, 0, 0, 0, 1], [-.25, -0.2, 0.665, 0, 0, 0, 1]] # Objects are turned upside down when w = 1?
  mesh_poses: []
- object_id: "Pringles" 
  key: "object"
  header_frame_id: "world"
  primitive_types: [[3]]
  primitive_dimensions: [[0.235, 0.04, 0.0]]
  primitive_poses: [[0.0, 0.0, 0.0, 0, 0, 0, 1]]
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
- object_id: "Cheezeit"
  key: "object"
  header_frame_id: "world"
  primitive_types: [[1]]
  primitive_dimensions: [[0.16, 0.065, 0.215]] # real size [[0.16, 0.065, 0.215]] 
  primitive_poses: [[0.0, 0.0, 0.0, 0, 0, 0, 1]]
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
- object_id: "Mustard"
  key: "object"
  header_frame_id: "world"
  primitive_types: [[1]]
  primitive_dimensions: [[.065, .03, 0.155]]
  primitive_poses: [[0.0, 0.0, 0.0, 0, 0, 0, 1]]
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
- object_id: "Spam" 
  key: "object"
  header_frame_id: "world"
  primitive_types: [[1]]
  primitive_dimensions: [[.1, .05, .085]]
  primitive_poses: [[0.0, 0.0, 0.0, 0, 0, 0, 1]]
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
- object_id: "sponge"
  key: "object"
  header_frame_id: "world"
  primitive_types: [[1]]
  primitive_dimensions: [[0.05, 0.1, 0.02]]
  primitive_poses: [[0.0, 0.0, 0.0, 0, 0, 0, 1]]
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
- object_id: "cylinder"
  key: "object"
  header_frame_id: "world"
  primitive_types: [[3]]
  primitive_dimensions: [[0.2, 0.02, 0.0]]
  primitive_poses: [[0.0, 0.0, 0.0, 0, 0, 0, 1]]
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
- object_id: "glass"
  key: "mesh"
  header_frame_id: "world"
  primitive_types: []
  primitive_dimensions: []
  primitive_poses: []
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
- object_id: "bottle"
  key: "mesh"
  header_frame_id: "world"
  primitive_types: []
  primitive_dimensions: []
  primitive_poses: []
  subframe_names: []
  subframe_poses: []
  mesh_poses: []
- object_id: "cup"
  key: "object"
  header_frame_id: "world"
  primitive_types: [[3]]
  primitive_dimensions: [[0.1, 0.02, 0.0]]
  primitive_poses: [[0.0, 0.0, 0.0, 0, 0, 0, 1]]
  subframe_names: []
  subframe_poses: []
  mesh_poses: []